### ISSUE TITLE
Unexpected checking result

### ISSUE THREAD

**Issue by muchang** [seahorn/seahorn#168]
```
void foo()
{
  static int last_align = -1;
  int dummy = 0;
  int align = (int)&dummy & 15;
  if (last_align < 0)
    last_align = align;
  else if (align != last_align)
    {__VERIFIER_error();}
}

int main()
{
	foo();
	foo();
	return 0;
}
```
In this case, `__VERIFIER_error();` is infeasible,  but Seahorn gives the sat result for this case which means  `__VERIFIER_error();` is feasible.

Command:` sea bpf <file_name.h>` or `sea pf <file_name.h>`
OS:Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by agurfinkel** [comment]
By default, SeaHorn makes no assumptions on alignment of any allocated memory. 
There is a new mode that attempts to generate a counterexample taking alignment into account, but this is highly experimental at this point. In general, we assume that the behavior of the program does not depend on alignment or particularities of the architecture (beyond very shallow features such as bitwidth of integers)

**Comment by caballa** [comment]
Both `bpf` and `pf` reason only about linear arithmetic and arrays.
The difference between `bpf` and `pf` is that the former unrolls loops statically while the latter doesn't.

Here, we need to reason at the bit-level. 
For that, we can run something like 

`sea bpf -m64 --inline --bmc=mono --log=cex <file_name.c>`

The key option is `--bmc=mono` which will enable the BMC engine that can reason at the bit-level. Currently, the BMC engines doesn't support functions so that's why we add the option `--inline`. The option `--log=cex` will print some messages, in particular the cex expressed as LLVM IR. Note also that I added the option `-m64` to tell Clang (called inside SeaHorn) that the architecture is 64 bits. 

Btw, yes I should write a [blog](http://seahorn.github.io/blog/) entry explaining all of this. 

Unfortunately, after all of this SeaHorn still reports a cex. 
The problem is that SeaHorn does not know that all addresses should be aligned. This is something that is not encoded in our memory model. Thus, it generates a cex where the first address is aligned but the second one does not, or viceversa. 

To deal with this kind of problems, SeaHorn has a feature that tries to generate an executable counterexample. In that process, SeaHorn will take the cex and it will try to generate an executable that can replay the cex. In doing that, it will impose constraints such as addresses must be aligned.  If it succeeds there is high chance that the cex is real. Otherwise, it's likely that the cex is spurious.  

If you try the command (this is described [here](http://seahorn.github.io/seahorn/cex/validation/2018/08/03/seahorn-cex-vstte18.html))
`sea exe-cex --bit-mem-precise --verify  --alloc-mem  --inline <file_name.c>`
you will see that a message like this

`__VERIFIER_error was not executed`

which means that the executable counterexample was not generated.

**Comment by muchang** [comment]
Thank you for your kind reply.
With `exe-cex` command it can indeed identify the feasibility of __VERIFIER_error.

I tried both `bpf` and `pf` because of the issue #155 which gives a case that Seahorn has the different performance between  `bpf` and `pf` configurations. May I ask why Seahorn gives different results for unrolling loops statically or not? There are also some other cases can trigger this problem.

**Comment by agurfinkel** [comment]
When loops are unrolled statically, different engines can be used to solve the problem. When the loops are not unrolled, seahorn must infer inductive invariants, and less techniques are available.

With static unrolling, the most precise technique is bit-precise bounded model checking. However, if that is not as precise as it can be since it uses an abstract memory model in which addresses do not have to be aligned.

**Comment by muchang** [comment]
Thank you for your explanation. I will not report such kind of bugs.
Here is another unexpected case:
```
int f(j)int j;{return++j>0;}
int main(){if(f((~0U)>>1))__VERIFIER_error();exit(0);}
```
In this case, `__VERIFIER_error();` is infeasible,  but Seahorn gives the sat result for this case which means  `__VERIFIER_error();` is feasible.

Command:sea pf <file_name.h>
OS:Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by agurfinkel** [comment]
According to LLVM, `___VERIFIER_error()` is feasible. Signed integer overflow is an undefined behavior. The program can be interpreted arbitrarily if this happens. While it is possible to use seahorn for undefined behavior, this is not the intention of the default configuration. We rely on compile analysis and optimizations to simplify the problem before verification. However, such analyses and optimizations assume absence of undefined behavior.

**Comment by muchang** [comment]
Thank you for your kind reply! I got that Seahorn will ignore the undefined behavior while doing the analysis.

Here is another case related to` volatile` keywords:
```
volatile int i = 10;
volatile int j = 10;

int main()
{
        int k = i % j;
        if (k != 0) __VERIFIER_error();
	return 0;
}
```
In this case, `__VERIFIER_error();` is obvouisly infeasible,  but Seahorn gives the sat result for this case which means  `__VERIFIER_error();` is feasible. At the same time, if I remove `volatile` from the code, Seahorn can give an expected result.

Command:sea pf <file_name.h>
OS:Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by agurfinkel** [comment]
In this example, there seems to be an interaction between the optimizer and bit-precision 
of the analysis. When `volatile` is removed, the code is optimized away in a bit-precise way.
When `volatile` is present, optimizer does not touch the code and the result depends on 
bit-precision of the analyzer. For examples like this where the main issue is soundness of arithmetic and not inductive invariants, use BMC engine that is bit-precise. 

The following command line command works correctly for me: 
```sea bpf --bmc /tmp/t3.c```

**Comment by muchang** [comment]
Thank you! But for the following arithmetic case, the checking result is still unexpected:
```
void
test (int x, int y, int q)
{
  if ((x / y) != q )
    __VERIFIER_error();
}

int
main ()
{
  test (7, 6, 1);
  test (-7, -6, 1);

  return 0;
}
```
 `__VERIFIER_error();` should be infeasible, Seahorn gives `sat` result with the command ` sea bpf --bmc /tmp/t3.c`.

The result can be expected if I test ` test (7, 6, 1);` and ` test (-7, -6, 1);` individually, such as:
```
int main ()
{
  test (7, 6, 1);

  return 0;
}
```
```
int main()
{
  test (-7, -6, 1);
  return 0;
}
```
OS:Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by agurfinkel** [comment]
The problem is solved by the front-end only. There appears to be a bug in the bmc engine that it does not warn that it was given a degenerate problem. If you run with 
`sea bpf --inline FILE.c`, there is a warning and correct result.

**Comment by muchang** [comment]
Thank you! This case still appears when running with `sea bpf FILE.c` and `sea pf FILE.c`.

BTW, Here is another case related to `array:
```
 int array[6] = { 1,2,3,4,5,6 };

int main()
{
  for (int i = 0; i < 5; i++)
    array[i] = 0;
  if (array[5] != 6)
    __VERIFIER_error();
  return 0;
}
```
 `__VERIFIER_error();` should be infeasible, Seahorn gives `sat` result with the commands ` sea bpf --bmc FILE.c` and `sea bpf -inline FILE.c`.

The result can be expected if checking `array[5] != 6` before `for` loop:
```
int array[6] = { 1,2,3,4,5,6 };

int main()
{
    if (array[5] != 6)
    __VERIFIER_error();
  for (int i = 0; i < 5; i++)
    array[i] = 0;
  return 0;
}
```
OS: Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by agurfinkel** [comment]
There are multiple things that conspire against this example. 

1. global initializers for arrays are not supported. It is an outstanding TODO item that is not very hard to do, but we never had the need in our applications.
2. the loop is optimized into `memset`. We do not support arbitrary `memset` operations. Again, some cases are not very hard, but we don't have a good use case so far.

Combination of `bpf -O0` seems to work. With bpf, the loop is unrolled and array accesses are simplified, while `-O0` prevents replacing everything by `memset`.

In general, it is very difficult to both scale and support all features of the language. So far, our development is driven by applications. We implement features and work-arounds based on applications. If there is a need, we can implement support for these examples (or help you understand the code to do it on your own). But it would be good to know what is the set of all the features that is required: array initialization, memset, pointer alignment, others?

**Comment by muchang** [comment]
Thank you for your reply. I have no actual application, I am just trying if Seahorn could satisfy some features may be required, and find some unexpected cases by the way.  
`bpf -O0`  can work well on the case above. But it still does not work well on another case about `array`:
```
int count = 0;

int
incr (void)
{
  return ++count;
}

int main()
{
  int arr[] = {1,2,3,4};
  arr[count++] = incr ();
  if (arr[count] != 3)
    __VERIFIER_error();
  return 0;
}
```
In this case, I avoid global initializers for the array, and the error label is not feasible. Seahorn gives `sat` result with the command ` sea bpf - O0 FILE.c`.  Does it because of the local initializers of the array are also not support?

OS: Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by kuhar** [comment]
@muchang Global initializers are supported for scalar variables and simple (non-nested) structs. You can see which global variables were handled by adding `--log=lower-gv-init` to your command.

I'll take a look at what's happening here.

**Comment by agurfinkel** [comment]
Local initializer are converted to a global initializer followed by a `memcpy` where the local initializer was expected. We don't support global initializers and `memcpy`. In your examples, these are easy to support by expanding them into multiple assignments.

**Comment by kuhar** [comment]
```
define i32 @main() #0 {
entry:
  %arr.i = alloca [4 x i32], align 4
  %0 = bitcast [4 x i32]* %arr.i to i8*
  call void @llvm.lifetime.start(i64 16, i8* %0)
  store i32 0, i32* @count, align 4 ; count = 0
  call void @seahorn.fn.enter() #3
  %1 = bitcast [4 x i32]* %arr.i to i8*
  call void @llvm.memcpy.p0i8.p0i8.i32(i8* %1, i8* bitcast ([4 x i32]* @main.arr to i8*), i32 16, i32 4, i1 false) #3
  %2 = call fastcc i32 @incr() #3
  %3 = load i32, i32* @count, align 4
  %4 = add nsw i32 %3, 1
  store i32 %4, i32* @count, align 4
  %5 = getelementptr inbounds [4 x i32], [4 x i32]* %arr.i, i32 0, i32 %3
  store i32 %2, i32* %5, align 4
  %6 = getelementptr inbounds [4 x i32], [4 x i32]* %arr.i, i32 0, i32 %4
  %7 = load i32, i32* %6, align 4
  %8 = icmp eq i32 %7, 3
  call void @verifier.assume.not(i1 %8)
  br label %9

; <label>:9                                       ; preds = %entry
  br label %verifier.error

verifier.error:                                   ; preds = %9
  call void @seahorn.fail()
  ret i32 42
}
```
It also looks like the final bitcode contains an unconditional branch to verifier.error.
You can get it by adding `--save-temps --temp-dir=./ -S` to your command and inspecting count.pp.ms.o.ul.cut.o.bc.

**Comment by agurfinkel** [comment]
@kuhar the branch is conditions. It is protected by a call to `verifier.assume.not`

**Comment by muchang** [comment]
Thank you, @kuhar and @agurfinkel.  Inspecting such `count.pp.ms.o.ul.cut.o.bc` middle files is helpful when analysising and reporting such cases. 
For struct, I have this struct related unexpected case:
```
struct s {
  int a:16,b;
};

struct s
f(struct s x)
{
  x.b = 1;
  return x;
}

int main()
{
  struct s i;
  i.a = 2;
  i = f(i);
  if (i.a != 2)
    __VERIFIER_error();
  return 0;
}
```
The ERROR label should be infeasible while Seahorn gives `sat` result with command `sea bpf -bmc -O0 --save-temps --temp-dir=./ -S FILE.c`.
I read the `.bc`  and guess it's related to the width of bit-field `a`, because if I change the width of bit-field `a` to 32, the result of seahorn is expected.

OS: Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by agurfinkel** [comment]
First, use `--inline` with `--bmc`, unless you really know what you are doing.

Second, the very small struct is passed by value and is accessed using `insertvalue` and `extractvalue` instructions. At the moment, these instructions are not modeled by `SeaHorn` causing the bug. When you change the bit-width of the field, the struct is too large to be passed by value and LLVM uses a different set of instructions to access it.

**Comment by muchang** [comment]
Thank you for your reply.  Here is another case related to string:
```
char * some_string;
void foo()
{
  if (!some_string)
    __VERIFIER_error();
}
void baz()
{
  some_string = "a";
  foo();
}
int main()
{
  baz();
  return 0;
}
```
The ERROR label should be infeasible while Seahorn gives `sat` result with command `sea bpf -inline -bmc -O0 --save-temps --temp-dir=./ -S FILE.c`. 
I read the `.bc` file, it seems that LLVM optimizes the assignment of variable `some_string` into global initialization but I am not sure.

OS: Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by agurfinkel** [comment]
I belive SeaHorn does not assume that global variables have non-zero addresses. 

The assignment itself definitely is compiled to a global initializer. The string `"a"` has to be allocated somewhere and it will not be allocated on the stack of `baz`.

**Comment by muchang** [comment]
Thank you, it makes sense.
Here is the case related to divide:
```
int test1 (int b, int c)
{
  int x = 2;
  if (b)
    return x / c;
  else
    return 1;
}
int main()
{
  if (test1(1, 1000) != 0)
    __VERIFIER_error();
  return 0;
}
```
The ERROR label should be infeasible while Seahorn gives `sat` result with command `sea bpf -inline -bmc -O0 --save-temps --temp-dir=./ -S FILE.c`. 
I read the `.bc` file but did not find any clue. If I replace `c` with `1000`, Seahorn works expected.

OS: Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by agurfinkel** [comment]
There seems to be a mistake in your command line options. Long options take two dashes. So it should be `--inline` and `--bmc`. Without `--inline`, the test function is not inlined and is treated as uninterpreted inside `main`. With `--inline`, the problem is discharged by the LLVM front-end

**Comment by muchang** [comment]
It is indeed a mistake in my command. But I can not get verification result with the command `sea bpf --inline --bmc -O0 test.c`.  The screenshot is as follow:
![capture](https://user-images.githubusercontent.com/3355874/49016741-4ed10400-f187-11e8-926e-97fa259cf96d.PNG)

BTW, here is another case may be related to `unsigned int` to `int` conversion: 
```
int
f1 (unsigned int n)
{
  return n % 0x33;
}

int
main ()
{
  int a = 0xaaaaaaaa;
  if (f1 (a) != 0x11)
    __VERIFIER_error();
  return 0;
}
```
The ERROR label should be infeasible while Seahorn gives `sat` result with command `sea bpf  --bmc -O0 --save-temps --temp-dir=./ -S FILE.c`.  If I use command `sea bpf --inline --bmc -O0 --save-temps --temp-dir=./ -S FILE.c`, Seahorn results in nothing just like screenshot above.

OS: Ubuntu 18.04
Revision: 21a1c0 built with docker

**Comment by agurfinkel** [comment]
You are hitting a bug that you saw before. When the pre-processing removes all assertions, the BMC engine is not invoked and no messages are printed. 

In both cases, without inlining, the function call in `main()` is treated as an uninterpreted function, and potential counterexample is found. With inlining, the problem is discharged by the pre-processor and never gets to the BMC engine.

**Comment by agurfinkel** [comment]
I've improved user message in the current development branch of seahorn. The change will appear in a docker image  `seahorn/seahorn-llvm5:nightly` within a day. You can check here for when it appears: https://hub.docker.com/r/seahorn/seahorn-llvm5/

**Comment by muchang** [comment]
Thank you, I am very looking forward to seeing this version :)

**Comment by muchang** [comment]
The new user message seems more clear. I could see that if inlining removes the assertions.
Here is another unexpected checking result:
```
int _br_4 = 0;
int _br_3 = 0;
typedef struct {
        int             x;
        int             y;
} point_t;

int printPoints(point_t a);
point_t toPoint(int x1, int y1);

int
main(int argc, char *argv[])
{

        printPoints(toPoint(0, 0));
        if (_br_3!=0) __VERIFIER_error();
        return 0;
}

int printPoints(point_t a)
{
        if (a.x != 0 || a.y != 0)
                { _br_3++; return 0; }
        else
                { _br_4++; return 1; }
}

point_t toPoint(int x1, int y1)
{
        point_t p;

        p.x = x1;
        p.y = y1;

        return p;
}
```
The ERROR label should be infeasible while Seahorn gives `sat` result with command `sea bpf  --bmc=mono -O0 --inline FILE.c`. 

BTW, if I use command `sea bpf  --bmc=mono -O0 --inline FILE.c` (without `--inline`), SeaHorn will print the user message: `WARNING: skipping a call to toPoint (recursive call?) WARNING: skipping a call to printPoints (recursive call?)`. But obviously, There is no recursive call in the program.

OS: Ubuntu 18.04
Revision: latest seahorn/seahorn-llvm5:nightly

**Comment by muchang** [comment]
Here is an unexpected case:
```
int _br_1 = 0;
void
test (const char *in)
{
  while (1)
    {
      if (*in == 'a')
	{ _br_1++;
	  const char *p = in + 1;
	  if (*p == 'b')
	    { _br_3++; return; }
	  in++;
	} 
    }
}

int main ()
{
  test ("aab");
  _stub();
  return 0;
}
void _stub() { if (!( (_br_1==2) )) __VERIFIER_error(); }
```
The ERROR label should be infeasible while Seahorn gives `sat` result with the command `sea bpf  --bmc=mono -O0 --inline FILE.c`. 

I also found many cases that Seahorn prints `WARNING: skipping a call to toPoint (recursive call?)` but obviously no recursive call in the code. Is it caused by the front-end or the BMC engine?

OS: Ubuntu 18.04
Revision: latest docker of seahorn/seahorn-llvm5:nightly

**Comment by agurfinkel** [comment]
I am working on improving soundness on small examples like this one. But it will take some time.
Thank you for the examples. They are very useful.

In this particular case, you are hitting issues in support for global array initializers. 
These are ignored, because they are hard to support well on complex examples.
The string `aab` in your example becomes a global variable with an array initializer.
SeaHorn treats it as non-deterministic. I'm working on improving error messages so that
cases like that are at least become self explanatory.

As to the `WARNING`. It means that `SeaHorn` found a call to a function during BMC.
Since functions are not expected at that point (they must be inlined), a warning is printed.
The most common case for a function call to remain even after inlining is that the function 
is recursive and cannot be inlined. The error message can be improved to check whether this
is in fact the case. Currently it just prints this as a conjecture.

**Comment by agurfinkel** [comment]
I don't have an explanation for why there are more `WARNINGS` with `llvm5` than with `llvm38`. If you have examples like this, I would be interested to investigate further. Perhaps some default settings for inliner have changed between the versions.

Thank you for another example. It is not related to bit-fields in structs. Without optimizations it is compiled into llvm struct values that are manipulated using `insertvalue` and `extractvalue` instructions. These are not yet supported -- i.e., abstracted by non-determinism. 

You can try allocating the structure on the heap and manipulate individual fields instead.

I would not call this soundness. We intentionally abstract many of the details of the semantics to scale the analysis. This is sound, but imprecise. I am working on a more precise (but maybe less scalable) semantics. Although, at the moment it does not support struct values either.

**Comment by muchang** [comment]
I tried some `WARNING` cases with both `llvm5` and `llvm38` and found that both of them have such `WARNING`. So it is not version related, I am sorry for the misleading. It just because of using `bmc` without `--inline`, as you mentioned SeaHorn's `bmc` engine doesn't support functions.

`WARNING` sometimes not precise in some other cases, for example:
```
struct S { unsigned char b, g, r, a; };
union U { struct S c; unsigned v; };

unsigned
bar ()
{
  union U z;
  z.c.a = 255;
  return z.v;
}

int
main ()
{
  union U c;
  c.v = bar ();
  if (c.c.a != 255)
    { __VERIFIER_error();}
  return 0;
}
```
For this case, with commandline `sea bpf --inline --bmc=mono -O0 -m64 --save-temps --temp-dir=./ -S  FILE.c` SearHorn prints the following message without check result:
```
WARNING: The program has no main() function.
WARNING: Possibly all assertions have been discharged by the front-end
WARNING: Alternatively, use --entry ENTRY option to specify acustom entry point
```
Actually, there are a main function in the program. The main function may be discharged by the front-end. It is a minor problem and not harmful, because these warnings could be seen as there are no feasible error label in the program.

===============================================================
Here is another unexpected checking result case:
```
int _br_1 = 0;

char *p = "abc\n";;

static int
is_end_of_statement (void)
{
  return *p == '\n';
}

void foo (void)
{
  while (!is_end_of_statement ())
    {_br_1++; p++; }
}

int
main (void)
{
  foo ();
  if ( _br_1!=3 ) __VERIFIER_error();
  return 0;
}
```
The ERROR label should be infeasible while Seahorn gives `sat` result with the command  `sea bpf --inline --bmc=mono -O0 -m64 --save-temps --temp-dir=./ -S  FILE.c` 
I checked the `.pp.ms.o.ul.cut.o.bc` file and make sure that the string `p` is initialized in main function.
Is it the same issue as supporting for global array initializers?

OS: Ubuntu 18.04
Version: seahorn/seahorn-llvm5:nightly

**Comment by caballa** [comment]
For the first example, it's discharged by the front-end.
For the second example, at least with 3.8 one problem is the lack of support for global array initializers.

**Comment by muchang** [comment]
The global array initialization free version of this code still has the same problem:
```
int _br_1 = 0;
static int
is_end_of_statement (char* p)
{
  return *p == '\n';
}

void foo (char *p)
{
  while (!is_end_of_statement (p))
    {_br_1++; p++; }
}

int
main (void)
{
  char *p = "abc\n";
  foo (p);
  if ( !((_br_1==3)) ) __VERIFIER_error();
  return 0;
}
```
The ERROR label should be infeasible while Seahorn gives sat result with the command `sea bpf --inline --bmc=mono -O0 -m64 --save-temps --temp-dir=./ -S FILE.c` 
I checked the `.pp.ms.o.ul.cut.o.bc` file and find the following LLVM IR:
```
@_br_1 = internal unnamed_addr global i32 0, align 4
@.str = private unnamed_addr constant [5 x i8] c"abc\0A\00", align 1
@llvm.used = appending global [8 x i8*] [i8* bitcast (void ()* @seahorn.fail to i8*), i8* bitcast (void (i1)* @verifier.assume to i8*), i8* bitcast (void (i1)* @verifier.assume.not to i8*), i8* bitcast (void ()* @verifier.error to i8*), i8* bitcast (void (i1)* @verifier.assume to i8*), i8* bitcast (void (i1)* @verifier.assume.not to i8*), i8* bitcast (void ()* @verifier.error to i8*), i8* bitcast (void ()* @seahorn.fail to i8*)], section "llvm.metadata"

; Function Attrs: nounwind uwtable
define private i32 @orig.main() local_unnamed_addr #0 {
  store i32 0, i32* @_br_1, align 4
  call void @seahorn.fn.enter() #2
  call void @seahorn.fn.enter() #2
  br label %1

; <label>:1:                                      ; preds = %0
  %.0.i = phi i8* [ getelementptr inbounds ([5 x i8], [5 x i8]* @.str, i64 0, i64 0), %0 ]
  call void @seahorn.fn.enter() #2
  %2 = load i8, i8* %.0.i, align 1, !tbaa !2
  %3 = icmp eq i8 %2, 10
  %4 = zext i1 %3 to i32
  %5 = icmp eq i32 %4, 0
  br i1 %5, label %6, label %foo.exit

; <label>:6:                                      ; preds = %1
  %7 = load i32, i32* @_br_1, align 4, !tbaa !5
  %8 = add nsw i32 %7, 1
  store i32 %8, i32* @_br_1, align 4, !tbaa !5
  %9 = getelementptr inbounds i8, i8* %.0.i, i64 1
  call void @verifier.assume.not(i1 true)
  br label %fake_latch_exit

foo.exit:                                         ; preds = %1
  %10 = load i32, i32* @_br_1, align 4, !tbaa !5
  %11 = icmp eq i32 %10, 3
  br i1 %11, label %13, label %12

; <label>:12:                                     ; preds = %foo.exit
  call void @verifier.error() #2
  unreachable

; <label>:13:                                     ; preds = %foo.exit
  ret i32 0

fake_latch_exit:                                  ; preds = %6
  unreachable
}
```
It seems that the string `abc\n` in the program becomes a global variable with an array initializer. Does it mean every string constant in the program will be treated as a global variable with an array initializer, so I would better not use the string constant in the program? 

===================================================================
Here is a case related to int array pointer:
```
int f (int *p, int *x)
{
  *p++;
  *x++;
  *x = *p;
  return 0;
}

int
main ()
{
  int u[2] = { 123, 234 };
  int x[2] = { 17689, 23456 };
  f (u, x);
  if (x[1] == 234)
    {__VERIFIER_error(); }
  return 0;
}
```
The ERROR label should be infeasible while Seahorn gives sat result with the command `sea bpf --inline --bmc=mono -O0 -m64 --save-temps --temp-dir=./ -S FILE.c` 

OS: Ubuntu 18.04
Version: seahorn/seahorn-llvm5:nightly

**Comment by agurfinkel** [comment]
Yes, all static strings have to be allocated somewhere. Usually they are moved to global memory.
I am working on extending initialization to arrays. I will take a look at the other example.

**Comment by agurfinkel** [comment]
I don't see why error label is infeasible. Perhaps the code `*p++; *x++;` is not as intended. Currently it increments the pointers, dereferences them, and then throws out the value. At the end `p` points to `u[1]` and `x` points to `x[1]`. `u[1]` is copied into `x[1]`, which makes `x[1] == 234` and error is reachable.

**Comment by muchang** [comment]
Oh, I am so sorry for the mistake, `if (x[1] == 234)` should be `if (x[1] != 234)`, the correct case is as follow:
```
int f (int *p, int *x)
{
  *p++;
  *x++;
  *x = *p;
  return 0;
}

int
main ()
{
  int u[2] = { 123, 234 };
  int x[2] = { 17689, 23456 };
  f (u, x);
  if (x[1] != 234)
    {__VERIFIER_error(); }
  return 0;
}
```
The ERROR label should be infeasible while Seahorn gives sat result with the command `sea bpf --inline --bmc=mono -O0 -m64 --save-temps --temp-dir=./ -S FILE.c`

**Comment by agurfinkel** [comment]
Yes, this should be unsat. I get unsat with my experimental mode...

**Comment by muchang** [comment]
I see, thank you. Maybe this issue has been fixed in your current developing version and my version is too old.

**Comment by agurfinkel** [comment]
It is part of nightly builds. The option is `--horn-bv2`. It is highly experimental at this point ;)

**Comment by muchang** [comment]
Thanks for your tip, I got the expected result with the experimental mode.
Here is another case:
```
static inline unsigned int
foo (unsigned int x)
{
  return (x >> 24) | ((x >> 8) & 0xff00) | ((x << 8) & 0xff0000) | (x << 24);
}

unsigned int
bar (unsigned long long *x)
{
  return foo (*x);
}

int
main ()
{
  unsigned long long l = foo(0xdeadbeefU) | 0xfeedbea800000000ULL;
  if (bar (&l) != 0xdeadbeefU)
    { __VERIFIER_error(); }
  return 0;
}
```
The ERROR label should be infeasible and no undefined behavior in the program (checked by `clang` and `compcert`) while Seahorn gives `sat` result with the command `sea bpf --inline --bmc=mono -O0 -m64 --save-temps --temp-dir=./ -S --horn-bv2 FILE.c`

OS: Ubuntu 18.04
Version: seahorn/seahorn-llvm5:nightly

**Comment by agurfinkel** [comment]
Fixed. Will appear in nightly during the next cron job. The problem was not handling `llvm.bswap.` intrinsic. 

You can use `--log=opsem` debug flag to get more visibility into what is not handled by `--horn-bv2` semantics. It tries to be verbose in what it is treating as non-deterministic.

Using `-m64` with `--horn-bv2` is not yet supported and might lead to strange behavior. 

Also, unaligned memory accesses might behave strangely (like accessing array of chars one byte at a time). There are extra switches for that, but it is not automatically detected at this point. You should assume that every memory operation reads/writes at least one word (32 bits).

**Comment by muchang** [comment]
Thank you so much for your explanation. 
Recently, I found two more unexpected checking result:
```
int k = 0;
int a, b;
int *p1, *p2;

int f() {
    int v = *p1 + *p2 - a;
    if (v == 1) {k++;
        p1 = p2;
        return v;
    } else {
        return 0;
    }
}

int main() {

    p1 = &a;
    p2 = &b;

    b = 1;
    a = 5;

    a--;

    a = f();

    if ( !((k==1)) ) __VERIFIER_error();;
    return 0;
}
```
```
void __CAUT_NOP_assert(int cond) {
  if (!(cond)) {
    __VERIFIER_error();
  } 
  return;
}

int *tmp;

int glob2 (int *pathbuf, int *pathlim)
{
  int *p;

  for (p = pathbuf; p <= pathlim; p++) {
    
    __CAUT_NOP_assert( p <= tmp);
    *p = 1;
  }
  return 0;
}

int main ()
{
  int pathbuf[2]={0,0};

  int *bound = pathbuf + 1;

  tmp = pathbuf + 2;

  glob2 (pathbuf, bound);

  return 0;
}
```
The `__VERIFIER_error();` label should be infeasible and no undefined behavior in the program (checked by `clang` and `compcert`) while Seahorn gives `sat` result with the command `sea bpf FILE.c`

OS: Ubuntu 18.04
Version: seahorn/seahorn-llvm5:nightly

**Comment by agurfinkel** [comment]
I'll check. Note that `bpf` requires `--inline` in the presence of functions.

**Comment by muchang** [comment]
Thank you for your tip! The second case can be solved by adding `--line`, but the first one still cannot produce the expected checking result, even in `bmc` mode.

By the way, May I know the Github version number of the SeaHorn in docker `seahorn\seahorn:latest`?

**Comment by muchang** [comment]
Here is another unexpected checking result case:
```
int st1 ;
int st2 ;
int a = 0;
int b = 0;
void check(void) 
{ 

  if (st1 + st2 <= 1) {a++;} 
  else {b++;}
}
int main(void) 
{
  st1 = -3;
  st2 = -1;
  check();
  if (b != 0 ) __VERIFIER_error();
  return 0;
}
```
The `__VERIFIER_error();` label should be infeasible and no undefined behavior in the program (checked by `clang` and `compcert`) while Seahorn gives `sat` result with the command `sea bpf --inline --bmc=mono FILE.c`

OS: Ubuntu 18.04
Version: seahorn/seahorn-llvm5:nightly

**Comment by agurfinkel** [comment]
Works correctly with the new bit-precise semantics that trades performance for correctness. The command line is: `sea bpf --inline --bmc=mono   --dsa=sea-cs  --horn-bv2 FILE.c`

In versions of seahorn, `seahorn --version` will return github sha. In older version it did not. We are not sure which exact version is on github except for the latest nightly.

**Comment by muchang** [comment]
Thank you for your reply to the case and the question! 
I got the expected result with the new command line.
